default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: angular-wshop-api_development

test:
  <<: *default
  database: angular-wshop-api_test

production:
  <<: *default
  database: angular-wshop-api_production
  username: angular-wshop-api
  password: <%= ENV['ANGULAR_WSHOP_API_DATABASE_PASSWORD'] %>